// Code generated by go-swagger; DO NOT EDIT.

package aiapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/Maritime-AI/mai-go-client/models"
)

// NewPostPartnersOrganizationsIDConverseParams creates a new PostPartnersOrganizationsIDConverseParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostPartnersOrganizationsIDConverseParams() *PostPartnersOrganizationsIDConverseParams {
	return &PostPartnersOrganizationsIDConverseParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostPartnersOrganizationsIDConverseParamsWithTimeout creates a new PostPartnersOrganizationsIDConverseParams object
// with the ability to set a timeout on a request.
func NewPostPartnersOrganizationsIDConverseParamsWithTimeout(timeout time.Duration) *PostPartnersOrganizationsIDConverseParams {
	return &PostPartnersOrganizationsIDConverseParams{
		timeout: timeout,
	}
}

// NewPostPartnersOrganizationsIDConverseParamsWithContext creates a new PostPartnersOrganizationsIDConverseParams object
// with the ability to set a context for a request.
func NewPostPartnersOrganizationsIDConverseParamsWithContext(ctx context.Context) *PostPartnersOrganizationsIDConverseParams {
	return &PostPartnersOrganizationsIDConverseParams{
		Context: ctx,
	}
}

// NewPostPartnersOrganizationsIDConverseParamsWithHTTPClient creates a new PostPartnersOrganizationsIDConverseParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostPartnersOrganizationsIDConverseParamsWithHTTPClient(client *http.Client) *PostPartnersOrganizationsIDConverseParams {
	return &PostPartnersOrganizationsIDConverseParams{
		HTTPClient: client,
	}
}

/*
PostPartnersOrganizationsIDConverseParams contains all the parameters to send to the API endpoint

	for the post partners organizations ID converse operation.

	Typically these are written to a http.Request.
*/
type PostPartnersOrganizationsIDConverseParams struct {

	// Body.
	Body *models.ChatMessageParams

	/* ID.

	   The unqiue partner organization reference id
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post partners organizations ID converse params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostPartnersOrganizationsIDConverseParams) WithDefaults() *PostPartnersOrganizationsIDConverseParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post partners organizations ID converse params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostPartnersOrganizationsIDConverseParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post partners organizations ID converse params
func (o *PostPartnersOrganizationsIDConverseParams) WithTimeout(timeout time.Duration) *PostPartnersOrganizationsIDConverseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post partners organizations ID converse params
func (o *PostPartnersOrganizationsIDConverseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post partners organizations ID converse params
func (o *PostPartnersOrganizationsIDConverseParams) WithContext(ctx context.Context) *PostPartnersOrganizationsIDConverseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post partners organizations ID converse params
func (o *PostPartnersOrganizationsIDConverseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post partners organizations ID converse params
func (o *PostPartnersOrganizationsIDConverseParams) WithHTTPClient(client *http.Client) *PostPartnersOrganizationsIDConverseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post partners organizations ID converse params
func (o *PostPartnersOrganizationsIDConverseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post partners organizations ID converse params
func (o *PostPartnersOrganizationsIDConverseParams) WithBody(body *models.ChatMessageParams) *PostPartnersOrganizationsIDConverseParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post partners organizations ID converse params
func (o *PostPartnersOrganizationsIDConverseParams) SetBody(body *models.ChatMessageParams) {
	o.Body = body
}

// WithID adds the id to the post partners organizations ID converse params
func (o *PostPartnersOrganizationsIDConverseParams) WithID(id string) *PostPartnersOrganizationsIDConverseParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the post partners organizations ID converse params
func (o *PostPartnersOrganizationsIDConverseParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PostPartnersOrganizationsIDConverseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
