// Code generated by go-swagger; DO NOT EDIT.

package healthcheck

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetReadinessReader is a Reader for the GetReadiness structure.
type GetReadinessReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetReadinessReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetReadinessOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /readiness] GetReadiness", response, response.Code())
	}
}

// NewGetReadinessOK creates a GetReadinessOK with default headers values
func NewGetReadinessOK() *GetReadinessOK {
	return &GetReadinessOK{}
}

/*
GetReadinessOK describes a response with status code 200, with default header values.

Successfully got user
*/
type GetReadinessOK struct {
}

// IsSuccess returns true when this get readiness o k response has a 2xx status code
func (o *GetReadinessOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get readiness o k response has a 3xx status code
func (o *GetReadinessOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get readiness o k response has a 4xx status code
func (o *GetReadinessOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get readiness o k response has a 5xx status code
func (o *GetReadinessOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get readiness o k response a status code equal to that given
func (o *GetReadinessOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get readiness o k response
func (o *GetReadinessOK) Code() int {
	return 200
}

func (o *GetReadinessOK) Error() string {
	return fmt.Sprintf("[GET /readiness][%d] getReadinessOK ", 200)
}

func (o *GetReadinessOK) String() string {
	return fmt.Sprintf("[GET /readiness][%d] getReadinessOK ", 200)
}

func (o *GetReadinessOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
