// Code generated by go-swagger; DO NOT EDIT.

package aiapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPartnersOrganizationsIDConversationSessionIDParams creates a new GetPartnersOrganizationsIDConversationSessionIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetPartnersOrganizationsIDConversationSessionIDParams() *GetPartnersOrganizationsIDConversationSessionIDParams {
	return &GetPartnersOrganizationsIDConversationSessionIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetPartnersOrganizationsIDConversationSessionIDParamsWithTimeout creates a new GetPartnersOrganizationsIDConversationSessionIDParams object
// with the ability to set a timeout on a request.
func NewGetPartnersOrganizationsIDConversationSessionIDParamsWithTimeout(timeout time.Duration) *GetPartnersOrganizationsIDConversationSessionIDParams {
	return &GetPartnersOrganizationsIDConversationSessionIDParams{
		timeout: timeout,
	}
}

// NewGetPartnersOrganizationsIDConversationSessionIDParamsWithContext creates a new GetPartnersOrganizationsIDConversationSessionIDParams object
// with the ability to set a context for a request.
func NewGetPartnersOrganizationsIDConversationSessionIDParamsWithContext(ctx context.Context) *GetPartnersOrganizationsIDConversationSessionIDParams {
	return &GetPartnersOrganizationsIDConversationSessionIDParams{
		Context: ctx,
	}
}

// NewGetPartnersOrganizationsIDConversationSessionIDParamsWithHTTPClient creates a new GetPartnersOrganizationsIDConversationSessionIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetPartnersOrganizationsIDConversationSessionIDParamsWithHTTPClient(client *http.Client) *GetPartnersOrganizationsIDConversationSessionIDParams {
	return &GetPartnersOrganizationsIDConversationSessionIDParams{
		HTTPClient: client,
	}
}

/*
GetPartnersOrganizationsIDConversationSessionIDParams contains all the parameters to send to the API endpoint

	for the get partners organizations ID conversation session ID operation.

	Typically these are written to a http.Request.
*/
type GetPartnersOrganizationsIDConversationSessionIDParams struct {

	/* ID.

	   The unqiue partner organization reference id
	*/
	ID string

	// SessionID.
	SessionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get partners organizations ID conversation session ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPartnersOrganizationsIDConversationSessionIDParams) WithDefaults() *GetPartnersOrganizationsIDConversationSessionIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get partners organizations ID conversation session ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPartnersOrganizationsIDConversationSessionIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get partners organizations ID conversation session ID params
func (o *GetPartnersOrganizationsIDConversationSessionIDParams) WithTimeout(timeout time.Duration) *GetPartnersOrganizationsIDConversationSessionIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get partners organizations ID conversation session ID params
func (o *GetPartnersOrganizationsIDConversationSessionIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get partners organizations ID conversation session ID params
func (o *GetPartnersOrganizationsIDConversationSessionIDParams) WithContext(ctx context.Context) *GetPartnersOrganizationsIDConversationSessionIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get partners organizations ID conversation session ID params
func (o *GetPartnersOrganizationsIDConversationSessionIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get partners organizations ID conversation session ID params
func (o *GetPartnersOrganizationsIDConversationSessionIDParams) WithHTTPClient(client *http.Client) *GetPartnersOrganizationsIDConversationSessionIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get partners organizations ID conversation session ID params
func (o *GetPartnersOrganizationsIDConversationSessionIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get partners organizations ID conversation session ID params
func (o *GetPartnersOrganizationsIDConversationSessionIDParams) WithID(id string) *GetPartnersOrganizationsIDConversationSessionIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get partners organizations ID conversation session ID params
func (o *GetPartnersOrganizationsIDConversationSessionIDParams) SetID(id string) {
	o.ID = id
}

// WithSessionID adds the sessionID to the get partners organizations ID conversation session ID params
func (o *GetPartnersOrganizationsIDConversationSessionIDParams) WithSessionID(sessionID string) *GetPartnersOrganizationsIDConversationSessionIDParams {
	o.SetSessionID(sessionID)
	return o
}

// SetSessionID adds the sessionId to the get partners organizations ID conversation session ID params
func (o *GetPartnersOrganizationsIDConversationSessionIDParams) SetSessionID(sessionID string) {
	o.SessionID = sessionID
}

// WriteToRequest writes these params to a swagger request
func (o *GetPartnersOrganizationsIDConversationSessionIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param session_id
	if err := r.SetPathParam("session_id", o.SessionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
