// Code generated by go-swagger; DO NOT EDIT.

package aiapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAdminsCustomersParams creates a new GetAdminsCustomersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAdminsCustomersParams() *GetAdminsCustomersParams {
	return &GetAdminsCustomersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAdminsCustomersParamsWithTimeout creates a new GetAdminsCustomersParams object
// with the ability to set a timeout on a request.
func NewGetAdminsCustomersParamsWithTimeout(timeout time.Duration) *GetAdminsCustomersParams {
	return &GetAdminsCustomersParams{
		timeout: timeout,
	}
}

// NewGetAdminsCustomersParamsWithContext creates a new GetAdminsCustomersParams object
// with the ability to set a context for a request.
func NewGetAdminsCustomersParamsWithContext(ctx context.Context) *GetAdminsCustomersParams {
	return &GetAdminsCustomersParams{
		Context: ctx,
	}
}

// NewGetAdminsCustomersParamsWithHTTPClient creates a new GetAdminsCustomersParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAdminsCustomersParamsWithHTTPClient(client *http.Client) *GetAdminsCustomersParams {
	return &GetAdminsCustomersParams{
		HTTPClient: client,
	}
}

/*
GetAdminsCustomersParams contains all the parameters to send to the API endpoint

	for the get admins customers operation.

	Typically these are written to a http.Request.
*/
type GetAdminsCustomersParams struct {

	// Limit.
	Limit *int64

	// Offset.
	Offset *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get admins customers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAdminsCustomersParams) WithDefaults() *GetAdminsCustomersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get admins customers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAdminsCustomersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get admins customers params
func (o *GetAdminsCustomersParams) WithTimeout(timeout time.Duration) *GetAdminsCustomersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get admins customers params
func (o *GetAdminsCustomersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get admins customers params
func (o *GetAdminsCustomersParams) WithContext(ctx context.Context) *GetAdminsCustomersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get admins customers params
func (o *GetAdminsCustomersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get admins customers params
func (o *GetAdminsCustomersParams) WithHTTPClient(client *http.Client) *GetAdminsCustomersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get admins customers params
func (o *GetAdminsCustomersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the get admins customers params
func (o *GetAdminsCustomersParams) WithLimit(limit *int64) *GetAdminsCustomersParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get admins customers params
func (o *GetAdminsCustomersParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the get admins customers params
func (o *GetAdminsCustomersParams) WithOffset(offset *int64) *GetAdminsCustomersParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get admins customers params
func (o *GetAdminsCustomersParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WriteToRequest writes these params to a swagger request
func (o *GetAdminsCustomersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
