// Code generated by go-swagger; DO NOT EDIT.

package aiapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Maritime-AI/mai-go-client/models"
)

// GetPartnersUsersIDConversationSessionIDReader is a Reader for the GetPartnersUsersIDConversationSessionID structure.
type GetPartnersUsersIDConversationSessionIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPartnersUsersIDConversationSessionIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPartnersUsersIDConversationSessionIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetPartnersUsersIDConversationSessionIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetPartnersUsersIDConversationSessionIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetPartnersUsersIDConversationSessionIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /partners/users/{id}/conversation/{session_id}] GetPartnersUsersIDConversationSessionID", response, response.Code())
	}
}

// NewGetPartnersUsersIDConversationSessionIDOK creates a GetPartnersUsersIDConversationSessionIDOK with default headers values
func NewGetPartnersUsersIDConversationSessionIDOK() *GetPartnersUsersIDConversationSessionIDOK {
	return &GetPartnersUsersIDConversationSessionIDOK{}
}

/*
GetPartnersUsersIDConversationSessionIDOK describes a response with status code 200, with default header values.

Success
*/
type GetPartnersUsersIDConversationSessionIDOK struct {
	Payload *models.ChatMessageResponse
}

// IsSuccess returns true when this get partners users Id conversation session Id o k response has a 2xx status code
func (o *GetPartnersUsersIDConversationSessionIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get partners users Id conversation session Id o k response has a 3xx status code
func (o *GetPartnersUsersIDConversationSessionIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get partners users Id conversation session Id o k response has a 4xx status code
func (o *GetPartnersUsersIDConversationSessionIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get partners users Id conversation session Id o k response has a 5xx status code
func (o *GetPartnersUsersIDConversationSessionIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get partners users Id conversation session Id o k response a status code equal to that given
func (o *GetPartnersUsersIDConversationSessionIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get partners users Id conversation session Id o k response
func (o *GetPartnersUsersIDConversationSessionIDOK) Code() int {
	return 200
}

func (o *GetPartnersUsersIDConversationSessionIDOK) Error() string {
	return fmt.Sprintf("[GET /partners/users/{id}/conversation/{session_id}][%d] getPartnersUsersIdConversationSessionIdOK  %+v", 200, o.Payload)
}

func (o *GetPartnersUsersIDConversationSessionIDOK) String() string {
	return fmt.Sprintf("[GET /partners/users/{id}/conversation/{session_id}][%d] getPartnersUsersIdConversationSessionIdOK  %+v", 200, o.Payload)
}

func (o *GetPartnersUsersIDConversationSessionIDOK) GetPayload() *models.ChatMessageResponse {
	return o.Payload
}

func (o *GetPartnersUsersIDConversationSessionIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ChatMessageResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPartnersUsersIDConversationSessionIDBadRequest creates a GetPartnersUsersIDConversationSessionIDBadRequest with default headers values
func NewGetPartnersUsersIDConversationSessionIDBadRequest() *GetPartnersUsersIDConversationSessionIDBadRequest {
	return &GetPartnersUsersIDConversationSessionIDBadRequest{}
}

/*
GetPartnersUsersIDConversationSessionIDBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetPartnersUsersIDConversationSessionIDBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this get partners users Id conversation session Id bad request response has a 2xx status code
func (o *GetPartnersUsersIDConversationSessionIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get partners users Id conversation session Id bad request response has a 3xx status code
func (o *GetPartnersUsersIDConversationSessionIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get partners users Id conversation session Id bad request response has a 4xx status code
func (o *GetPartnersUsersIDConversationSessionIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get partners users Id conversation session Id bad request response has a 5xx status code
func (o *GetPartnersUsersIDConversationSessionIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get partners users Id conversation session Id bad request response a status code equal to that given
func (o *GetPartnersUsersIDConversationSessionIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get partners users Id conversation session Id bad request response
func (o *GetPartnersUsersIDConversationSessionIDBadRequest) Code() int {
	return 400
}

func (o *GetPartnersUsersIDConversationSessionIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /partners/users/{id}/conversation/{session_id}][%d] getPartnersUsersIdConversationSessionIdBadRequest  %+v", 400, o.Payload)
}

func (o *GetPartnersUsersIDConversationSessionIDBadRequest) String() string {
	return fmt.Sprintf("[GET /partners/users/{id}/conversation/{session_id}][%d] getPartnersUsersIdConversationSessionIdBadRequest  %+v", 400, o.Payload)
}

func (o *GetPartnersUsersIDConversationSessionIDBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetPartnersUsersIDConversationSessionIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPartnersUsersIDConversationSessionIDUnauthorized creates a GetPartnersUsersIDConversationSessionIDUnauthorized with default headers values
func NewGetPartnersUsersIDConversationSessionIDUnauthorized() *GetPartnersUsersIDConversationSessionIDUnauthorized {
	return &GetPartnersUsersIDConversationSessionIDUnauthorized{}
}

/*
GetPartnersUsersIDConversationSessionIDUnauthorized describes a response with status code 401, with default header values.

Not Authorized
*/
type GetPartnersUsersIDConversationSessionIDUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this get partners users Id conversation session Id unauthorized response has a 2xx status code
func (o *GetPartnersUsersIDConversationSessionIDUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get partners users Id conversation session Id unauthorized response has a 3xx status code
func (o *GetPartnersUsersIDConversationSessionIDUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get partners users Id conversation session Id unauthorized response has a 4xx status code
func (o *GetPartnersUsersIDConversationSessionIDUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get partners users Id conversation session Id unauthorized response has a 5xx status code
func (o *GetPartnersUsersIDConversationSessionIDUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get partners users Id conversation session Id unauthorized response a status code equal to that given
func (o *GetPartnersUsersIDConversationSessionIDUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get partners users Id conversation session Id unauthorized response
func (o *GetPartnersUsersIDConversationSessionIDUnauthorized) Code() int {
	return 401
}

func (o *GetPartnersUsersIDConversationSessionIDUnauthorized) Error() string {
	return fmt.Sprintf("[GET /partners/users/{id}/conversation/{session_id}][%d] getPartnersUsersIdConversationSessionIdUnauthorized  %+v", 401, o.Payload)
}

func (o *GetPartnersUsersIDConversationSessionIDUnauthorized) String() string {
	return fmt.Sprintf("[GET /partners/users/{id}/conversation/{session_id}][%d] getPartnersUsersIdConversationSessionIdUnauthorized  %+v", 401, o.Payload)
}

func (o *GetPartnersUsersIDConversationSessionIDUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetPartnersUsersIDConversationSessionIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPartnersUsersIDConversationSessionIDInternalServerError creates a GetPartnersUsersIDConversationSessionIDInternalServerError with default headers values
func NewGetPartnersUsersIDConversationSessionIDInternalServerError() *GetPartnersUsersIDConversationSessionIDInternalServerError {
	return &GetPartnersUsersIDConversationSessionIDInternalServerError{}
}

/*
GetPartnersUsersIDConversationSessionIDInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetPartnersUsersIDConversationSessionIDInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this get partners users Id conversation session Id internal server error response has a 2xx status code
func (o *GetPartnersUsersIDConversationSessionIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get partners users Id conversation session Id internal server error response has a 3xx status code
func (o *GetPartnersUsersIDConversationSessionIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get partners users Id conversation session Id internal server error response has a 4xx status code
func (o *GetPartnersUsersIDConversationSessionIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get partners users Id conversation session Id internal server error response has a 5xx status code
func (o *GetPartnersUsersIDConversationSessionIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get partners users Id conversation session Id internal server error response a status code equal to that given
func (o *GetPartnersUsersIDConversationSessionIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get partners users Id conversation session Id internal server error response
func (o *GetPartnersUsersIDConversationSessionIDInternalServerError) Code() int {
	return 500
}

func (o *GetPartnersUsersIDConversationSessionIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /partners/users/{id}/conversation/{session_id}][%d] getPartnersUsersIdConversationSessionIdInternalServerError  %+v", 500, o.Payload)
}

func (o *GetPartnersUsersIDConversationSessionIDInternalServerError) String() string {
	return fmt.Sprintf("[GET /partners/users/{id}/conversation/{session_id}][%d] getPartnersUsersIdConversationSessionIdInternalServerError  %+v", 500, o.Payload)
}

func (o *GetPartnersUsersIDConversationSessionIDInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetPartnersUsersIDConversationSessionIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
