// Code generated by go-swagger; DO NOT EDIT.

package aiapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	
	"github.com/Maritime-AI/mai-go-client/models"
)

// GetPartnersOrganizationsIDConversationSessionIDReader is a Reader for the GetPartnersOrganizationsIDConversationSessionID structure.
type GetPartnersOrganizationsIDConversationSessionIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPartnersOrganizationsIDConversationSessionIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPartnersOrganizationsIDConversationSessionIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetPartnersOrganizationsIDConversationSessionIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetPartnersOrganizationsIDConversationSessionIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetPartnersOrganizationsIDConversationSessionIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /partners/organizations/{id}/conversation/{session_id}] GetPartnersOrganizationsIDConversationSessionID", response, response.Code())
	}
}

// NewGetPartnersOrganizationsIDConversationSessionIDOK creates a GetPartnersOrganizationsIDConversationSessionIDOK with default headers values
func NewGetPartnersOrganizationsIDConversationSessionIDOK() *GetPartnersOrganizationsIDConversationSessionIDOK {
	return &GetPartnersOrganizationsIDConversationSessionIDOK{}
}

/*
GetPartnersOrganizationsIDConversationSessionIDOK describes a response with status code 200, with default header values.

Success
*/
type GetPartnersOrganizationsIDConversationSessionIDOK struct {
	Payload *models.ChatMessageResponse
}

// IsSuccess returns true when this get partners organizations Id conversation session Id o k response has a 2xx status code
func (o *GetPartnersOrganizationsIDConversationSessionIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get partners organizations Id conversation session Id o k response has a 3xx status code
func (o *GetPartnersOrganizationsIDConversationSessionIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get partners organizations Id conversation session Id o k response has a 4xx status code
func (o *GetPartnersOrganizationsIDConversationSessionIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get partners organizations Id conversation session Id o k response has a 5xx status code
func (o *GetPartnersOrganizationsIDConversationSessionIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get partners organizations Id conversation session Id o k response a status code equal to that given
func (o *GetPartnersOrganizationsIDConversationSessionIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get partners organizations Id conversation session Id o k response
func (o *GetPartnersOrganizationsIDConversationSessionIDOK) Code() int {
	return 200
}

func (o *GetPartnersOrganizationsIDConversationSessionIDOK) Error() string {
	return fmt.Sprintf("[GET /partners/organizations/{id}/conversation/{session_id}][%d] getPartnersOrganizationsIdConversationSessionIdOK  %+v", 200, o.Payload)
}

func (o *GetPartnersOrganizationsIDConversationSessionIDOK) String() string {
	return fmt.Sprintf("[GET /partners/organizations/{id}/conversation/{session_id}][%d] getPartnersOrganizationsIdConversationSessionIdOK  %+v", 200, o.Payload)
}

func (o *GetPartnersOrganizationsIDConversationSessionIDOK) GetPayload() *models.ChatMessageResponse {
	return o.Payload
}

func (o *GetPartnersOrganizationsIDConversationSessionIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ChatMessageResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPartnersOrganizationsIDConversationSessionIDBadRequest creates a GetPartnersOrganizationsIDConversationSessionIDBadRequest with default headers values
func NewGetPartnersOrganizationsIDConversationSessionIDBadRequest() *GetPartnersOrganizationsIDConversationSessionIDBadRequest {
	return &GetPartnersOrganizationsIDConversationSessionIDBadRequest{}
}

/*
GetPartnersOrganizationsIDConversationSessionIDBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetPartnersOrganizationsIDConversationSessionIDBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this get partners organizations Id conversation session Id bad request response has a 2xx status code
func (o *GetPartnersOrganizationsIDConversationSessionIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get partners organizations Id conversation session Id bad request response has a 3xx status code
func (o *GetPartnersOrganizationsIDConversationSessionIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get partners organizations Id conversation session Id bad request response has a 4xx status code
func (o *GetPartnersOrganizationsIDConversationSessionIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get partners organizations Id conversation session Id bad request response has a 5xx status code
func (o *GetPartnersOrganizationsIDConversationSessionIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get partners organizations Id conversation session Id bad request response a status code equal to that given
func (o *GetPartnersOrganizationsIDConversationSessionIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get partners organizations Id conversation session Id bad request response
func (o *GetPartnersOrganizationsIDConversationSessionIDBadRequest) Code() int {
	return 400
}

func (o *GetPartnersOrganizationsIDConversationSessionIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /partners/organizations/{id}/conversation/{session_id}][%d] getPartnersOrganizationsIdConversationSessionIdBadRequest  %+v", 400, o.Payload)
}

func (o *GetPartnersOrganizationsIDConversationSessionIDBadRequest) String() string {
	return fmt.Sprintf("[GET /partners/organizations/{id}/conversation/{session_id}][%d] getPartnersOrganizationsIdConversationSessionIdBadRequest  %+v", 400, o.Payload)
}

func (o *GetPartnersOrganizationsIDConversationSessionIDBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetPartnersOrganizationsIDConversationSessionIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPartnersOrganizationsIDConversationSessionIDUnauthorized creates a GetPartnersOrganizationsIDConversationSessionIDUnauthorized with default headers values
func NewGetPartnersOrganizationsIDConversationSessionIDUnauthorized() *GetPartnersOrganizationsIDConversationSessionIDUnauthorized {
	return &GetPartnersOrganizationsIDConversationSessionIDUnauthorized{}
}

/*
GetPartnersOrganizationsIDConversationSessionIDUnauthorized describes a response with status code 401, with default header values.

Not Authorized
*/
type GetPartnersOrganizationsIDConversationSessionIDUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this get partners organizations Id conversation session Id unauthorized response has a 2xx status code
func (o *GetPartnersOrganizationsIDConversationSessionIDUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get partners organizations Id conversation session Id unauthorized response has a 3xx status code
func (o *GetPartnersOrganizationsIDConversationSessionIDUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get partners organizations Id conversation session Id unauthorized response has a 4xx status code
func (o *GetPartnersOrganizationsIDConversationSessionIDUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get partners organizations Id conversation session Id unauthorized response has a 5xx status code
func (o *GetPartnersOrganizationsIDConversationSessionIDUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get partners organizations Id conversation session Id unauthorized response a status code equal to that given
func (o *GetPartnersOrganizationsIDConversationSessionIDUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get partners organizations Id conversation session Id unauthorized response
func (o *GetPartnersOrganizationsIDConversationSessionIDUnauthorized) Code() int {
	return 401
}

func (o *GetPartnersOrganizationsIDConversationSessionIDUnauthorized) Error() string {
	return fmt.Sprintf("[GET /partners/organizations/{id}/conversation/{session_id}][%d] getPartnersOrganizationsIdConversationSessionIdUnauthorized  %+v", 401, o.Payload)
}

func (o *GetPartnersOrganizationsIDConversationSessionIDUnauthorized) String() string {
	return fmt.Sprintf("[GET /partners/organizations/{id}/conversation/{session_id}][%d] getPartnersOrganizationsIdConversationSessionIdUnauthorized  %+v", 401, o.Payload)
}

func (o *GetPartnersOrganizationsIDConversationSessionIDUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetPartnersOrganizationsIDConversationSessionIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPartnersOrganizationsIDConversationSessionIDInternalServerError creates a GetPartnersOrganizationsIDConversationSessionIDInternalServerError with default headers values
func NewGetPartnersOrganizationsIDConversationSessionIDInternalServerError() *GetPartnersOrganizationsIDConversationSessionIDInternalServerError {
	return &GetPartnersOrganizationsIDConversationSessionIDInternalServerError{}
}

/*
GetPartnersOrganizationsIDConversationSessionIDInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetPartnersOrganizationsIDConversationSessionIDInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this get partners organizations Id conversation session Id internal server error response has a 2xx status code
func (o *GetPartnersOrganizationsIDConversationSessionIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get partners organizations Id conversation session Id internal server error response has a 3xx status code
func (o *GetPartnersOrganizationsIDConversationSessionIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get partners organizations Id conversation session Id internal server error response has a 4xx status code
func (o *GetPartnersOrganizationsIDConversationSessionIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get partners organizations Id conversation session Id internal server error response has a 5xx status code
func (o *GetPartnersOrganizationsIDConversationSessionIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get partners organizations Id conversation session Id internal server error response a status code equal to that given
func (o *GetPartnersOrganizationsIDConversationSessionIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get partners organizations Id conversation session Id internal server error response
func (o *GetPartnersOrganizationsIDConversationSessionIDInternalServerError) Code() int {
	return 500
}

func (o *GetPartnersOrganizationsIDConversationSessionIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /partners/organizations/{id}/conversation/{session_id}][%d] getPartnersOrganizationsIdConversationSessionIdInternalServerError  %+v", 500, o.Payload)
}

func (o *GetPartnersOrganizationsIDConversationSessionIDInternalServerError) String() string {
	return fmt.Sprintf("[GET /partners/organizations/{id}/conversation/{session_id}][%d] getPartnersOrganizationsIdConversationSessionIdInternalServerError  %+v", 500, o.Payload)
}

func (o *GetPartnersOrganizationsIDConversationSessionIDInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetPartnersOrganizationsIDConversationSessionIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
