// Code generated by go-swagger; DO NOT EDIT.

package aiapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAdminsCustomersUploadsParams creates a new GetAdminsCustomersUploadsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAdminsCustomersUploadsParams() *GetAdminsCustomersUploadsParams {
	return &GetAdminsCustomersUploadsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAdminsCustomersUploadsParamsWithTimeout creates a new GetAdminsCustomersUploadsParams object
// with the ability to set a timeout on a request.
func NewGetAdminsCustomersUploadsParamsWithTimeout(timeout time.Duration) *GetAdminsCustomersUploadsParams {
	return &GetAdminsCustomersUploadsParams{
		timeout: timeout,
	}
}

// NewGetAdminsCustomersUploadsParamsWithContext creates a new GetAdminsCustomersUploadsParams object
// with the ability to set a context for a request.
func NewGetAdminsCustomersUploadsParamsWithContext(ctx context.Context) *GetAdminsCustomersUploadsParams {
	return &GetAdminsCustomersUploadsParams{
		Context: ctx,
	}
}

// NewGetAdminsCustomersUploadsParamsWithHTTPClient creates a new GetAdminsCustomersUploadsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAdminsCustomersUploadsParamsWithHTTPClient(client *http.Client) *GetAdminsCustomersUploadsParams {
	return &GetAdminsCustomersUploadsParams{
		HTTPClient: client,
	}
}

/*
GetAdminsCustomersUploadsParams contains all the parameters to send to the API endpoint

	for the get admins customers uploads operation.

	Typically these are written to a http.Request.
*/
type GetAdminsCustomersUploadsParams struct {

	// Limit.
	Limit int64

	// Offset.
	Offset int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get admins customers uploads params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAdminsCustomersUploadsParams) WithDefaults() *GetAdminsCustomersUploadsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get admins customers uploads params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAdminsCustomersUploadsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get admins customers uploads params
func (o *GetAdminsCustomersUploadsParams) WithTimeout(timeout time.Duration) *GetAdminsCustomersUploadsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get admins customers uploads params
func (o *GetAdminsCustomersUploadsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get admins customers uploads params
func (o *GetAdminsCustomersUploadsParams) WithContext(ctx context.Context) *GetAdminsCustomersUploadsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get admins customers uploads params
func (o *GetAdminsCustomersUploadsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get admins customers uploads params
func (o *GetAdminsCustomersUploadsParams) WithHTTPClient(client *http.Client) *GetAdminsCustomersUploadsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get admins customers uploads params
func (o *GetAdminsCustomersUploadsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the get admins customers uploads params
func (o *GetAdminsCustomersUploadsParams) WithLimit(limit int64) *GetAdminsCustomersUploadsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get admins customers uploads params
func (o *GetAdminsCustomersUploadsParams) SetLimit(limit int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the get admins customers uploads params
func (o *GetAdminsCustomersUploadsParams) WithOffset(offset int64) *GetAdminsCustomersUploadsParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get admins customers uploads params
func (o *GetAdminsCustomersUploadsParams) SetOffset(offset int64) {
	o.Offset = offset
}

// WriteToRequest writes these params to a swagger request
func (o *GetAdminsCustomersUploadsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param limit
	qrLimit := o.Limit
	qLimit := swag.FormatInt64(qrLimit)
	if qLimit != "" {

		if err := r.SetQueryParam("limit", qLimit); err != nil {
			return err
		}
	}

	// query param offset
	qrOffset := o.Offset
	qOffset := swag.FormatInt64(qrOffset)
	if qOffset != "" {

		if err := r.SetQueryParam("offset", qOffset); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
