// Code generated by go-swagger; DO NOT EDIT.

package aiapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Maritime-AI/mai-go-client/models"
)

// PostPartnersOrganizationsIDSearchReader is a Reader for the PostPartnersOrganizationsIDSearch structure.
type PostPartnersOrganizationsIDSearchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostPartnersOrganizationsIDSearchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostPartnersOrganizationsIDSearchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostPartnersOrganizationsIDSearchBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostPartnersOrganizationsIDSearchUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostPartnersOrganizationsIDSearchInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /partners/organizations/{id}/search] PostPartnersOrganizationsIDSearch", response, response.Code())
	}
}

// NewPostPartnersOrganizationsIDSearchOK creates a PostPartnersOrganizationsIDSearchOK with default headers values
func NewPostPartnersOrganizationsIDSearchOK() *PostPartnersOrganizationsIDSearchOK {
	return &PostPartnersOrganizationsIDSearchOK{}
}

/*
PostPartnersOrganizationsIDSearchOK describes a response with status code 200, with default header values.

Success
*/
type PostPartnersOrganizationsIDSearchOK struct {
	Payload *models.SearchResponse
}

// IsSuccess returns true when this post partners organizations Id search o k response has a 2xx status code
func (o *PostPartnersOrganizationsIDSearchOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post partners organizations Id search o k response has a 3xx status code
func (o *PostPartnersOrganizationsIDSearchOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post partners organizations Id search o k response has a 4xx status code
func (o *PostPartnersOrganizationsIDSearchOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post partners organizations Id search o k response has a 5xx status code
func (o *PostPartnersOrganizationsIDSearchOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post partners organizations Id search o k response a status code equal to that given
func (o *PostPartnersOrganizationsIDSearchOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post partners organizations Id search o k response
func (o *PostPartnersOrganizationsIDSearchOK) Code() int {
	return 200
}

func (o *PostPartnersOrganizationsIDSearchOK) Error() string {
	return fmt.Sprintf("[POST /partners/organizations/{id}/search][%d] postPartnersOrganizationsIdSearchOK  %+v", 200, o.Payload)
}

func (o *PostPartnersOrganizationsIDSearchOK) String() string {
	return fmt.Sprintf("[POST /partners/organizations/{id}/search][%d] postPartnersOrganizationsIdSearchOK  %+v", 200, o.Payload)
}

func (o *PostPartnersOrganizationsIDSearchOK) GetPayload() *models.SearchResponse {
	return o.Payload
}

func (o *PostPartnersOrganizationsIDSearchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SearchResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostPartnersOrganizationsIDSearchBadRequest creates a PostPartnersOrganizationsIDSearchBadRequest with default headers values
func NewPostPartnersOrganizationsIDSearchBadRequest() *PostPartnersOrganizationsIDSearchBadRequest {
	return &PostPartnersOrganizationsIDSearchBadRequest{}
}

/*
PostPartnersOrganizationsIDSearchBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostPartnersOrganizationsIDSearchBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this post partners organizations Id search bad request response has a 2xx status code
func (o *PostPartnersOrganizationsIDSearchBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post partners organizations Id search bad request response has a 3xx status code
func (o *PostPartnersOrganizationsIDSearchBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post partners organizations Id search bad request response has a 4xx status code
func (o *PostPartnersOrganizationsIDSearchBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post partners organizations Id search bad request response has a 5xx status code
func (o *PostPartnersOrganizationsIDSearchBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post partners organizations Id search bad request response a status code equal to that given
func (o *PostPartnersOrganizationsIDSearchBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post partners organizations Id search bad request response
func (o *PostPartnersOrganizationsIDSearchBadRequest) Code() int {
	return 400
}

func (o *PostPartnersOrganizationsIDSearchBadRequest) Error() string {
	return fmt.Sprintf("[POST /partners/organizations/{id}/search][%d] postPartnersOrganizationsIdSearchBadRequest  %+v", 400, o.Payload)
}

func (o *PostPartnersOrganizationsIDSearchBadRequest) String() string {
	return fmt.Sprintf("[POST /partners/organizations/{id}/search][%d] postPartnersOrganizationsIdSearchBadRequest  %+v", 400, o.Payload)
}

func (o *PostPartnersOrganizationsIDSearchBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostPartnersOrganizationsIDSearchBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostPartnersOrganizationsIDSearchUnauthorized creates a PostPartnersOrganizationsIDSearchUnauthorized with default headers values
func NewPostPartnersOrganizationsIDSearchUnauthorized() *PostPartnersOrganizationsIDSearchUnauthorized {
	return &PostPartnersOrganizationsIDSearchUnauthorized{}
}

/*
PostPartnersOrganizationsIDSearchUnauthorized describes a response with status code 401, with default header values.

Not Authorized
*/
type PostPartnersOrganizationsIDSearchUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this post partners organizations Id search unauthorized response has a 2xx status code
func (o *PostPartnersOrganizationsIDSearchUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post partners organizations Id search unauthorized response has a 3xx status code
func (o *PostPartnersOrganizationsIDSearchUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post partners organizations Id search unauthorized response has a 4xx status code
func (o *PostPartnersOrganizationsIDSearchUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post partners organizations Id search unauthorized response has a 5xx status code
func (o *PostPartnersOrganizationsIDSearchUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post partners organizations Id search unauthorized response a status code equal to that given
func (o *PostPartnersOrganizationsIDSearchUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post partners organizations Id search unauthorized response
func (o *PostPartnersOrganizationsIDSearchUnauthorized) Code() int {
	return 401
}

func (o *PostPartnersOrganizationsIDSearchUnauthorized) Error() string {
	return fmt.Sprintf("[POST /partners/organizations/{id}/search][%d] postPartnersOrganizationsIdSearchUnauthorized  %+v", 401, o.Payload)
}

func (o *PostPartnersOrganizationsIDSearchUnauthorized) String() string {
	return fmt.Sprintf("[POST /partners/organizations/{id}/search][%d] postPartnersOrganizationsIdSearchUnauthorized  %+v", 401, o.Payload)
}

func (o *PostPartnersOrganizationsIDSearchUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostPartnersOrganizationsIDSearchUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostPartnersOrganizationsIDSearchInternalServerError creates a PostPartnersOrganizationsIDSearchInternalServerError with default headers values
func NewPostPartnersOrganizationsIDSearchInternalServerError() *PostPartnersOrganizationsIDSearchInternalServerError {
	return &PostPartnersOrganizationsIDSearchInternalServerError{}
}

/*
PostPartnersOrganizationsIDSearchInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type PostPartnersOrganizationsIDSearchInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this post partners organizations Id search internal server error response has a 2xx status code
func (o *PostPartnersOrganizationsIDSearchInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post partners organizations Id search internal server error response has a 3xx status code
func (o *PostPartnersOrganizationsIDSearchInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post partners organizations Id search internal server error response has a 4xx status code
func (o *PostPartnersOrganizationsIDSearchInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post partners organizations Id search internal server error response has a 5xx status code
func (o *PostPartnersOrganizationsIDSearchInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post partners organizations Id search internal server error response a status code equal to that given
func (o *PostPartnersOrganizationsIDSearchInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post partners organizations Id search internal server error response
func (o *PostPartnersOrganizationsIDSearchInternalServerError) Code() int {
	return 500
}

func (o *PostPartnersOrganizationsIDSearchInternalServerError) Error() string {
	return fmt.Sprintf("[POST /partners/organizations/{id}/search][%d] postPartnersOrganizationsIdSearchInternalServerError  %+v", 500, o.Payload)
}

func (o *PostPartnersOrganizationsIDSearchInternalServerError) String() string {
	return fmt.Sprintf("[POST /partners/organizations/{id}/search][%d] postPartnersOrganizationsIdSearchInternalServerError  %+v", 500, o.Payload)
}

func (o *PostPartnersOrganizationsIDSearchInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostPartnersOrganizationsIDSearchInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
