// Code generated by go-swagger; DO NOT EDIT.

package aiapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/Maritime-AI/mai-go-client/models"
)

// NewPostAdminsLoginParams creates a new PostAdminsLoginParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAdminsLoginParams() *PostAdminsLoginParams {
	return &PostAdminsLoginParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAdminsLoginParamsWithTimeout creates a new PostAdminsLoginParams object
// with the ability to set a timeout on a request.
func NewPostAdminsLoginParamsWithTimeout(timeout time.Duration) *PostAdminsLoginParams {
	return &PostAdminsLoginParams{
		timeout: timeout,
	}
}

// NewPostAdminsLoginParamsWithContext creates a new PostAdminsLoginParams object
// with the ability to set a context for a request.
func NewPostAdminsLoginParamsWithContext(ctx context.Context) *PostAdminsLoginParams {
	return &PostAdminsLoginParams{
		Context: ctx,
	}
}

// NewPostAdminsLoginParamsWithHTTPClient creates a new PostAdminsLoginParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAdminsLoginParamsWithHTTPClient(client *http.Client) *PostAdminsLoginParams {
	return &PostAdminsLoginParams{
		HTTPClient: client,
	}
}

/*
PostAdminsLoginParams contains all the parameters to send to the API endpoint

	for the post admins login operation.

	Typically these are written to a http.Request.
*/
type PostAdminsLoginParams struct {

	// Body.
	Body *models.AdminAuthParams

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post admins login params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAdminsLoginParams) WithDefaults() *PostAdminsLoginParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post admins login params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAdminsLoginParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post admins login params
func (o *PostAdminsLoginParams) WithTimeout(timeout time.Duration) *PostAdminsLoginParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post admins login params
func (o *PostAdminsLoginParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post admins login params
func (o *PostAdminsLoginParams) WithContext(ctx context.Context) *PostAdminsLoginParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post admins login params
func (o *PostAdminsLoginParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post admins login params
func (o *PostAdminsLoginParams) WithHTTPClient(client *http.Client) *PostAdminsLoginParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post admins login params
func (o *PostAdminsLoginParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post admins login params
func (o *PostAdminsLoginParams) WithBody(body *models.AdminAuthParams) *PostAdminsLoginParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post admins login params
func (o *PostAdminsLoginParams) SetBody(body *models.AdminAuthParams) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostAdminsLoginParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
