// Code generated by go-swagger; DO NOT EDIT.

package aiapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/Maritime-AI/mai-go-client/models"
)

// NewPostPartnersCrewParams creates a new PostPartnersCrewParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostPartnersCrewParams() *PostPartnersCrewParams {
	return &PostPartnersCrewParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostPartnersCrewParamsWithTimeout creates a new PostPartnersCrewParams object
// with the ability to set a timeout on a request.
func NewPostPartnersCrewParamsWithTimeout(timeout time.Duration) *PostPartnersCrewParams {
	return &PostPartnersCrewParams{
		timeout: timeout,
	}
}

// NewPostPartnersCrewParamsWithContext creates a new PostPartnersCrewParams object
// with the ability to set a context for a request.
func NewPostPartnersCrewParamsWithContext(ctx context.Context) *PostPartnersCrewParams {
	return &PostPartnersCrewParams{
		Context: ctx,
	}
}

// NewPostPartnersCrewParamsWithHTTPClient creates a new PostPartnersCrewParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostPartnersCrewParamsWithHTTPClient(client *http.Client) *PostPartnersCrewParams {
	return &PostPartnersCrewParams{
		HTTPClient: client,
	}
}

/*
PostPartnersCrewParams contains all the parameters to send to the API endpoint

	for the post partners crew operation.

	Typically these are written to a http.Request.
*/
type PostPartnersCrewParams struct {

	// Body.
	Body *models.CrewParams

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post partners crew params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostPartnersCrewParams) WithDefaults() *PostPartnersCrewParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post partners crew params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostPartnersCrewParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post partners crew params
func (o *PostPartnersCrewParams) WithTimeout(timeout time.Duration) *PostPartnersCrewParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post partners crew params
func (o *PostPartnersCrewParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post partners crew params
func (o *PostPartnersCrewParams) WithContext(ctx context.Context) *PostPartnersCrewParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post partners crew params
func (o *PostPartnersCrewParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post partners crew params
func (o *PostPartnersCrewParams) WithHTTPClient(client *http.Client) *PostPartnersCrewParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post partners crew params
func (o *PostPartnersCrewParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post partners crew params
func (o *PostPartnersCrewParams) WithBody(body *models.CrewParams) *PostPartnersCrewParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post partners crew params
func (o *PostPartnersCrewParams) SetBody(body *models.CrewParams) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostPartnersCrewParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
