// Code generated by go-swagger; DO NOT EDIT.

package aiapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/Maritime-AI/mai-go-client/models"
)

// NewPostCrewParams creates a new PostCrewParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostCrewParams() *PostCrewParams {
	return &PostCrewParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostCrewParamsWithTimeout creates a new PostCrewParams object
// with the ability to set a timeout on a request.
func NewPostCrewParamsWithTimeout(timeout time.Duration) *PostCrewParams {
	return &PostCrewParams{
		timeout: timeout,
	}
}

// NewPostCrewParamsWithContext creates a new PostCrewParams object
// with the ability to set a context for a request.
func NewPostCrewParamsWithContext(ctx context.Context) *PostCrewParams {
	return &PostCrewParams{
		Context: ctx,
	}
}

// NewPostCrewParamsWithHTTPClient creates a new PostCrewParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostCrewParamsWithHTTPClient(client *http.Client) *PostCrewParams {
	return &PostCrewParams{
		HTTPClient: client,
	}
}

/*
PostCrewParams contains all the parameters to send to the API endpoint

	for the post crew operation.

	Typically these are written to a http.Request.
*/
type PostCrewParams struct {

	// Body.
	Body *models.CrewParams

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post crew params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostCrewParams) WithDefaults() *PostCrewParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post crew params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostCrewParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post crew params
func (o *PostCrewParams) WithTimeout(timeout time.Duration) *PostCrewParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post crew params
func (o *PostCrewParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post crew params
func (o *PostCrewParams) WithContext(ctx context.Context) *PostCrewParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post crew params
func (o *PostCrewParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post crew params
func (o *PostCrewParams) WithHTTPClient(client *http.Client) *PostCrewParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post crew params
func (o *PostCrewParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post crew params
func (o *PostCrewParams) WithBody(body *models.CrewParams) *PostCrewParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post crew params
func (o *PostCrewParams) SetBody(body *models.CrewParams) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostCrewParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
