// Code generated by go-swagger; DO NOT EDIT.

package aiapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/Maritime-AI/mai-go-client/models"
)

// NewPostAdminsPartnersOrganizationsIDConverseParams creates a new PostAdminsPartnersOrganizationsIDConverseParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAdminsPartnersOrganizationsIDConverseParams() *PostAdminsPartnersOrganizationsIDConverseParams {
	return &PostAdminsPartnersOrganizationsIDConverseParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAdminsPartnersOrganizationsIDConverseParamsWithTimeout creates a new PostAdminsPartnersOrganizationsIDConverseParams object
// with the ability to set a timeout on a request.
func NewPostAdminsPartnersOrganizationsIDConverseParamsWithTimeout(timeout time.Duration) *PostAdminsPartnersOrganizationsIDConverseParams {
	return &PostAdminsPartnersOrganizationsIDConverseParams{
		timeout: timeout,
	}
}

// NewPostAdminsPartnersOrganizationsIDConverseParamsWithContext creates a new PostAdminsPartnersOrganizationsIDConverseParams object
// with the ability to set a context for a request.
func NewPostAdminsPartnersOrganizationsIDConverseParamsWithContext(ctx context.Context) *PostAdminsPartnersOrganizationsIDConverseParams {
	return &PostAdminsPartnersOrganizationsIDConverseParams{
		Context: ctx,
	}
}

// NewPostAdminsPartnersOrganizationsIDConverseParamsWithHTTPClient creates a new PostAdminsPartnersOrganizationsIDConverseParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAdminsPartnersOrganizationsIDConverseParamsWithHTTPClient(client *http.Client) *PostAdminsPartnersOrganizationsIDConverseParams {
	return &PostAdminsPartnersOrganizationsIDConverseParams{
		HTTPClient: client,
	}
}

/*
PostAdminsPartnersOrganizationsIDConverseParams contains all the parameters to send to the API endpoint

	for the post admins partners organizations ID converse operation.

	Typically these are written to a http.Request.
*/
type PostAdminsPartnersOrganizationsIDConverseParams struct {

	// Body.
	Body *models.ChatMessageParams

	/* ID.

	   The unqiue partner organization reference id
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post admins partners organizations ID converse params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAdminsPartnersOrganizationsIDConverseParams) WithDefaults() *PostAdminsPartnersOrganizationsIDConverseParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post admins partners organizations ID converse params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAdminsPartnersOrganizationsIDConverseParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post admins partners organizations ID converse params
func (o *PostAdminsPartnersOrganizationsIDConverseParams) WithTimeout(timeout time.Duration) *PostAdminsPartnersOrganizationsIDConverseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post admins partners organizations ID converse params
func (o *PostAdminsPartnersOrganizationsIDConverseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post admins partners organizations ID converse params
func (o *PostAdminsPartnersOrganizationsIDConverseParams) WithContext(ctx context.Context) *PostAdminsPartnersOrganizationsIDConverseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post admins partners organizations ID converse params
func (o *PostAdminsPartnersOrganizationsIDConverseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post admins partners organizations ID converse params
func (o *PostAdminsPartnersOrganizationsIDConverseParams) WithHTTPClient(client *http.Client) *PostAdminsPartnersOrganizationsIDConverseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post admins partners organizations ID converse params
func (o *PostAdminsPartnersOrganizationsIDConverseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post admins partners organizations ID converse params
func (o *PostAdminsPartnersOrganizationsIDConverseParams) WithBody(body *models.ChatMessageParams) *PostAdminsPartnersOrganizationsIDConverseParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post admins partners organizations ID converse params
func (o *PostAdminsPartnersOrganizationsIDConverseParams) SetBody(body *models.ChatMessageParams) {
	o.Body = body
}

// WithID adds the id to the post admins partners organizations ID converse params
func (o *PostAdminsPartnersOrganizationsIDConverseParams) WithID(id string) *PostAdminsPartnersOrganizationsIDConverseParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the post admins partners organizations ID converse params
func (o *PostAdminsPartnersOrganizationsIDConverseParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PostAdminsPartnersOrganizationsIDConverseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
