// Code generated by go-swagger; DO NOT EDIT.

package aiapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/Maritime-AI/mai-go-client/models"
)

// NewPostAdminLoginParams creates a new PostAdminLoginParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAdminLoginParams() *PostAdminLoginParams {
	return &PostAdminLoginParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAdminLoginParamsWithTimeout creates a new PostAdminLoginParams object
// with the ability to set a timeout on a request.
func NewPostAdminLoginParamsWithTimeout(timeout time.Duration) *PostAdminLoginParams {
	return &PostAdminLoginParams{
		timeout: timeout,
	}
}

// NewPostAdminLoginParamsWithContext creates a new PostAdminLoginParams object
// with the ability to set a context for a request.
func NewPostAdminLoginParamsWithContext(ctx context.Context) *PostAdminLoginParams {
	return &PostAdminLoginParams{
		Context: ctx,
	}
}

// NewPostAdminLoginParamsWithHTTPClient creates a new PostAdminLoginParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAdminLoginParamsWithHTTPClient(client *http.Client) *PostAdminLoginParams {
	return &PostAdminLoginParams{
		HTTPClient: client,
	}
}

/*
PostAdminLoginParams contains all the parameters to send to the API endpoint

	for the post admin login operation.

	Typically these are written to a http.Request.
*/
type PostAdminLoginParams struct {

	// Body.
	Body *models.AdminAuthParams

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post admin login params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAdminLoginParams) WithDefaults() *PostAdminLoginParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post admin login params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAdminLoginParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post admin login params
func (o *PostAdminLoginParams) WithTimeout(timeout time.Duration) *PostAdminLoginParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post admin login params
func (o *PostAdminLoginParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post admin login params
func (o *PostAdminLoginParams) WithContext(ctx context.Context) *PostAdminLoginParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post admin login params
func (o *PostAdminLoginParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post admin login params
func (o *PostAdminLoginParams) WithHTTPClient(client *http.Client) *PostAdminLoginParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post admin login params
func (o *PostAdminLoginParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post admin login params
func (o *PostAdminLoginParams) WithBody(body *models.AdminAuthParams) *PostAdminLoginParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post admin login params
func (o *PostAdminLoginParams) SetBody(body *models.AdminAuthParams) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostAdminLoginParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
