// Code generated by go-swagger; DO NOT EDIT.

package aiapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Maritime-AI/mai-go-client/models"
)

// PostAdminsLoginReader is a Reader for the PostAdminsLogin structure.
type PostAdminsLoginReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAdminsLoginReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAdminsLoginOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAdminsLoginBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostAdminsLoginUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostAdminsLoginInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /admins/login] PostAdminsLogin", response, response.Code())
	}
}

// NewPostAdminsLoginOK creates a PostAdminsLoginOK with default headers values
func NewPostAdminsLoginOK() *PostAdminsLoginOK {
	return &PostAdminsLoginOK{}
}

/*
PostAdminsLoginOK describes a response with status code 200, with default header values.

Success
*/
type PostAdminsLoginOK struct {
	Payload *models.AuthResponse
}

// IsSuccess returns true when this post admins login o k response has a 2xx status code
func (o *PostAdminsLoginOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post admins login o k response has a 3xx status code
func (o *PostAdminsLoginOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post admins login o k response has a 4xx status code
func (o *PostAdminsLoginOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post admins login o k response has a 5xx status code
func (o *PostAdminsLoginOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post admins login o k response a status code equal to that given
func (o *PostAdminsLoginOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post admins login o k response
func (o *PostAdminsLoginOK) Code() int {
	return 200
}

func (o *PostAdminsLoginOK) Error() string {
	return fmt.Sprintf("[POST /admins/login][%d] postAdminsLoginOK  %+v", 200, o.Payload)
}

func (o *PostAdminsLoginOK) String() string {
	return fmt.Sprintf("[POST /admins/login][%d] postAdminsLoginOK  %+v", 200, o.Payload)
}

func (o *PostAdminsLoginOK) GetPayload() *models.AuthResponse {
	return o.Payload
}

func (o *PostAdminsLoginOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AuthResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAdminsLoginBadRequest creates a PostAdminsLoginBadRequest with default headers values
func NewPostAdminsLoginBadRequest() *PostAdminsLoginBadRequest {
	return &PostAdminsLoginBadRequest{}
}

/*
PostAdminsLoginBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostAdminsLoginBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this post admins login bad request response has a 2xx status code
func (o *PostAdminsLoginBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post admins login bad request response has a 3xx status code
func (o *PostAdminsLoginBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post admins login bad request response has a 4xx status code
func (o *PostAdminsLoginBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post admins login bad request response has a 5xx status code
func (o *PostAdminsLoginBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post admins login bad request response a status code equal to that given
func (o *PostAdminsLoginBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post admins login bad request response
func (o *PostAdminsLoginBadRequest) Code() int {
	return 400
}

func (o *PostAdminsLoginBadRequest) Error() string {
	return fmt.Sprintf("[POST /admins/login][%d] postAdminsLoginBadRequest  %+v", 400, o.Payload)
}

func (o *PostAdminsLoginBadRequest) String() string {
	return fmt.Sprintf("[POST /admins/login][%d] postAdminsLoginBadRequest  %+v", 400, o.Payload)
}

func (o *PostAdminsLoginBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostAdminsLoginBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAdminsLoginUnauthorized creates a PostAdminsLoginUnauthorized with default headers values
func NewPostAdminsLoginUnauthorized() *PostAdminsLoginUnauthorized {
	return &PostAdminsLoginUnauthorized{}
}

/*
PostAdminsLoginUnauthorized describes a response with status code 401, with default header values.

Not Authorized
*/
type PostAdminsLoginUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this post admins login unauthorized response has a 2xx status code
func (o *PostAdminsLoginUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post admins login unauthorized response has a 3xx status code
func (o *PostAdminsLoginUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post admins login unauthorized response has a 4xx status code
func (o *PostAdminsLoginUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post admins login unauthorized response has a 5xx status code
func (o *PostAdminsLoginUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post admins login unauthorized response a status code equal to that given
func (o *PostAdminsLoginUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post admins login unauthorized response
func (o *PostAdminsLoginUnauthorized) Code() int {
	return 401
}

func (o *PostAdminsLoginUnauthorized) Error() string {
	return fmt.Sprintf("[POST /admins/login][%d] postAdminsLoginUnauthorized  %+v", 401, o.Payload)
}

func (o *PostAdminsLoginUnauthorized) String() string {
	return fmt.Sprintf("[POST /admins/login][%d] postAdminsLoginUnauthorized  %+v", 401, o.Payload)
}

func (o *PostAdminsLoginUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostAdminsLoginUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAdminsLoginInternalServerError creates a PostAdminsLoginInternalServerError with default headers values
func NewPostAdminsLoginInternalServerError() *PostAdminsLoginInternalServerError {
	return &PostAdminsLoginInternalServerError{}
}

/*
PostAdminsLoginInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type PostAdminsLoginInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this post admins login internal server error response has a 2xx status code
func (o *PostAdminsLoginInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post admins login internal server error response has a 3xx status code
func (o *PostAdminsLoginInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post admins login internal server error response has a 4xx status code
func (o *PostAdminsLoginInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post admins login internal server error response has a 5xx status code
func (o *PostAdminsLoginInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post admins login internal server error response a status code equal to that given
func (o *PostAdminsLoginInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post admins login internal server error response
func (o *PostAdminsLoginInternalServerError) Code() int {
	return 500
}

func (o *PostAdminsLoginInternalServerError) Error() string {
	return fmt.Sprintf("[POST /admins/login][%d] postAdminsLoginInternalServerError  %+v", 500, o.Payload)
}

func (o *PostAdminsLoginInternalServerError) String() string {
	return fmt.Sprintf("[POST /admins/login][%d] postAdminsLoginInternalServerError  %+v", 500, o.Payload)
}

func (o *PostAdminsLoginInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostAdminsLoginInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
