// Code generated by go-swagger; DO NOT EDIT.

package aiapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/Maritime-AI/mai-go-client/models"
)

// NewPostPartnersUsersIDConverseParams creates a new PostPartnersUsersIDConverseParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostPartnersUsersIDConverseParams() *PostPartnersUsersIDConverseParams {
	return &PostPartnersUsersIDConverseParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostPartnersUsersIDConverseParamsWithTimeout creates a new PostPartnersUsersIDConverseParams object
// with the ability to set a timeout on a request.
func NewPostPartnersUsersIDConverseParamsWithTimeout(timeout time.Duration) *PostPartnersUsersIDConverseParams {
	return &PostPartnersUsersIDConverseParams{
		timeout: timeout,
	}
}

// NewPostPartnersUsersIDConverseParamsWithContext creates a new PostPartnersUsersIDConverseParams object
// with the ability to set a context for a request.
func NewPostPartnersUsersIDConverseParamsWithContext(ctx context.Context) *PostPartnersUsersIDConverseParams {
	return &PostPartnersUsersIDConverseParams{
		Context: ctx,
	}
}

// NewPostPartnersUsersIDConverseParamsWithHTTPClient creates a new PostPartnersUsersIDConverseParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostPartnersUsersIDConverseParamsWithHTTPClient(client *http.Client) *PostPartnersUsersIDConverseParams {
	return &PostPartnersUsersIDConverseParams{
		HTTPClient: client,
	}
}

/*
PostPartnersUsersIDConverseParams contains all the parameters to send to the API endpoint

	for the post partners users ID converse operation.

	Typically these are written to a http.Request.
*/
type PostPartnersUsersIDConverseParams struct {

	// Body.
	Body *models.ChatMessageParams

	/* ID.

	   The unqiue partner user reference id
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post partners users ID converse params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostPartnersUsersIDConverseParams) WithDefaults() *PostPartnersUsersIDConverseParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post partners users ID converse params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostPartnersUsersIDConverseParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post partners users ID converse params
func (o *PostPartnersUsersIDConverseParams) WithTimeout(timeout time.Duration) *PostPartnersUsersIDConverseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post partners users ID converse params
func (o *PostPartnersUsersIDConverseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post partners users ID converse params
func (o *PostPartnersUsersIDConverseParams) WithContext(ctx context.Context) *PostPartnersUsersIDConverseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post partners users ID converse params
func (o *PostPartnersUsersIDConverseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post partners users ID converse params
func (o *PostPartnersUsersIDConverseParams) WithHTTPClient(client *http.Client) *PostPartnersUsersIDConverseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post partners users ID converse params
func (o *PostPartnersUsersIDConverseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post partners users ID converse params
func (o *PostPartnersUsersIDConverseParams) WithBody(body *models.ChatMessageParams) *PostPartnersUsersIDConverseParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post partners users ID converse params
func (o *PostPartnersUsersIDConverseParams) SetBody(body *models.ChatMessageParams) {
	o.Body = body
}

// WithID adds the id to the post partners users ID converse params
func (o *PostPartnersUsersIDConverseParams) WithID(id string) *PostPartnersUsersIDConverseParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the post partners users ID converse params
func (o *PostPartnersUsersIDConverseParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PostPartnersUsersIDConverseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
