// Code generated by go-swagger; DO NOT EDIT.

package aiapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Maritime-AI/mai-go-client/models"
)

// PostAdminsPartnersOrganizationsIDConverseReader is a Reader for the PostAdminsPartnersOrganizationsIDConverse structure.
type PostAdminsPartnersOrganizationsIDConverseReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAdminsPartnersOrganizationsIDConverseReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAdminsPartnersOrganizationsIDConverseOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAdminsPartnersOrganizationsIDConverseBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostAdminsPartnersOrganizationsIDConverseUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostAdminsPartnersOrganizationsIDConverseInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /admins/partners/organizations/{id}/converse] PostAdminsPartnersOrganizationsIDConverse", response, response.Code())
	}
}

// NewPostAdminsPartnersOrganizationsIDConverseOK creates a PostAdminsPartnersOrganizationsIDConverseOK with default headers values
func NewPostAdminsPartnersOrganizationsIDConverseOK() *PostAdminsPartnersOrganizationsIDConverseOK {
	return &PostAdminsPartnersOrganizationsIDConverseOK{}
}

/*
PostAdminsPartnersOrganizationsIDConverseOK describes a response with status code 200, with default header values.

Success
*/
type PostAdminsPartnersOrganizationsIDConverseOK struct {
	Payload *models.ChatMessageResponse
}

// IsSuccess returns true when this post admins partners organizations Id converse o k response has a 2xx status code
func (o *PostAdminsPartnersOrganizationsIDConverseOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post admins partners organizations Id converse o k response has a 3xx status code
func (o *PostAdminsPartnersOrganizationsIDConverseOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post admins partners organizations Id converse o k response has a 4xx status code
func (o *PostAdminsPartnersOrganizationsIDConverseOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post admins partners organizations Id converse o k response has a 5xx status code
func (o *PostAdminsPartnersOrganizationsIDConverseOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post admins partners organizations Id converse o k response a status code equal to that given
func (o *PostAdminsPartnersOrganizationsIDConverseOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post admins partners organizations Id converse o k response
func (o *PostAdminsPartnersOrganizationsIDConverseOK) Code() int {
	return 200
}

func (o *PostAdminsPartnersOrganizationsIDConverseOK) Error() string {
	return fmt.Sprintf("[POST /admins/partners/organizations/{id}/converse][%d] postAdminsPartnersOrganizationsIdConverseOK  %+v", 200, o.Payload)
}

func (o *PostAdminsPartnersOrganizationsIDConverseOK) String() string {
	return fmt.Sprintf("[POST /admins/partners/organizations/{id}/converse][%d] postAdminsPartnersOrganizationsIdConverseOK  %+v", 200, o.Payload)
}

func (o *PostAdminsPartnersOrganizationsIDConverseOK) GetPayload() *models.ChatMessageResponse {
	return o.Payload
}

func (o *PostAdminsPartnersOrganizationsIDConverseOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ChatMessageResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAdminsPartnersOrganizationsIDConverseBadRequest creates a PostAdminsPartnersOrganizationsIDConverseBadRequest with default headers values
func NewPostAdminsPartnersOrganizationsIDConverseBadRequest() *PostAdminsPartnersOrganizationsIDConverseBadRequest {
	return &PostAdminsPartnersOrganizationsIDConverseBadRequest{}
}

/*
PostAdminsPartnersOrganizationsIDConverseBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostAdminsPartnersOrganizationsIDConverseBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this post admins partners organizations Id converse bad request response has a 2xx status code
func (o *PostAdminsPartnersOrganizationsIDConverseBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post admins partners organizations Id converse bad request response has a 3xx status code
func (o *PostAdminsPartnersOrganizationsIDConverseBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post admins partners organizations Id converse bad request response has a 4xx status code
func (o *PostAdminsPartnersOrganizationsIDConverseBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post admins partners organizations Id converse bad request response has a 5xx status code
func (o *PostAdminsPartnersOrganizationsIDConverseBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post admins partners organizations Id converse bad request response a status code equal to that given
func (o *PostAdminsPartnersOrganizationsIDConverseBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post admins partners organizations Id converse bad request response
func (o *PostAdminsPartnersOrganizationsIDConverseBadRequest) Code() int {
	return 400
}

func (o *PostAdminsPartnersOrganizationsIDConverseBadRequest) Error() string {
	return fmt.Sprintf("[POST /admins/partners/organizations/{id}/converse][%d] postAdminsPartnersOrganizationsIdConverseBadRequest  %+v", 400, o.Payload)
}

func (o *PostAdminsPartnersOrganizationsIDConverseBadRequest) String() string {
	return fmt.Sprintf("[POST /admins/partners/organizations/{id}/converse][%d] postAdminsPartnersOrganizationsIdConverseBadRequest  %+v", 400, o.Payload)
}

func (o *PostAdminsPartnersOrganizationsIDConverseBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostAdminsPartnersOrganizationsIDConverseBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAdminsPartnersOrganizationsIDConverseUnauthorized creates a PostAdminsPartnersOrganizationsIDConverseUnauthorized with default headers values
func NewPostAdminsPartnersOrganizationsIDConverseUnauthorized() *PostAdminsPartnersOrganizationsIDConverseUnauthorized {
	return &PostAdminsPartnersOrganizationsIDConverseUnauthorized{}
}

/*
PostAdminsPartnersOrganizationsIDConverseUnauthorized describes a response with status code 401, with default header values.

Not Authorized
*/
type PostAdminsPartnersOrganizationsIDConverseUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this post admins partners organizations Id converse unauthorized response has a 2xx status code
func (o *PostAdminsPartnersOrganizationsIDConverseUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post admins partners organizations Id converse unauthorized response has a 3xx status code
func (o *PostAdminsPartnersOrganizationsIDConverseUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post admins partners organizations Id converse unauthorized response has a 4xx status code
func (o *PostAdminsPartnersOrganizationsIDConverseUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post admins partners organizations Id converse unauthorized response has a 5xx status code
func (o *PostAdminsPartnersOrganizationsIDConverseUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post admins partners organizations Id converse unauthorized response a status code equal to that given
func (o *PostAdminsPartnersOrganizationsIDConverseUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post admins partners organizations Id converse unauthorized response
func (o *PostAdminsPartnersOrganizationsIDConverseUnauthorized) Code() int {
	return 401
}

func (o *PostAdminsPartnersOrganizationsIDConverseUnauthorized) Error() string {
	return fmt.Sprintf("[POST /admins/partners/organizations/{id}/converse][%d] postAdminsPartnersOrganizationsIdConverseUnauthorized  %+v", 401, o.Payload)
}

func (o *PostAdminsPartnersOrganizationsIDConverseUnauthorized) String() string {
	return fmt.Sprintf("[POST /admins/partners/organizations/{id}/converse][%d] postAdminsPartnersOrganizationsIdConverseUnauthorized  %+v", 401, o.Payload)
}

func (o *PostAdminsPartnersOrganizationsIDConverseUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostAdminsPartnersOrganizationsIDConverseUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAdminsPartnersOrganizationsIDConverseInternalServerError creates a PostAdminsPartnersOrganizationsIDConverseInternalServerError with default headers values
func NewPostAdminsPartnersOrganizationsIDConverseInternalServerError() *PostAdminsPartnersOrganizationsIDConverseInternalServerError {
	return &PostAdminsPartnersOrganizationsIDConverseInternalServerError{}
}

/*
PostAdminsPartnersOrganizationsIDConverseInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type PostAdminsPartnersOrganizationsIDConverseInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this post admins partners organizations Id converse internal server error response has a 2xx status code
func (o *PostAdminsPartnersOrganizationsIDConverseInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post admins partners organizations Id converse internal server error response has a 3xx status code
func (o *PostAdminsPartnersOrganizationsIDConverseInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post admins partners organizations Id converse internal server error response has a 4xx status code
func (o *PostAdminsPartnersOrganizationsIDConverseInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post admins partners organizations Id converse internal server error response has a 5xx status code
func (o *PostAdminsPartnersOrganizationsIDConverseInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post admins partners organizations Id converse internal server error response a status code equal to that given
func (o *PostAdminsPartnersOrganizationsIDConverseInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post admins partners organizations Id converse internal server error response
func (o *PostAdminsPartnersOrganizationsIDConverseInternalServerError) Code() int {
	return 500
}

func (o *PostAdminsPartnersOrganizationsIDConverseInternalServerError) Error() string {
	return fmt.Sprintf("[POST /admins/partners/organizations/{id}/converse][%d] postAdminsPartnersOrganizationsIdConverseInternalServerError  %+v", 500, o.Payload)
}

func (o *PostAdminsPartnersOrganizationsIDConverseInternalServerError) String() string {
	return fmt.Sprintf("[POST /admins/partners/organizations/{id}/converse][%d] postAdminsPartnersOrganizationsIdConverseInternalServerError  %+v", 500, o.Payload)
}

func (o *PostAdminsPartnersOrganizationsIDConverseInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostAdminsPartnersOrganizationsIDConverseInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
