// Code generated by go-swagger; DO NOT EDIT.

package aiapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Maritime-AI/mai-go-client/models"
)

// PostCrewReader is a Reader for the PostCrew structure.
type PostCrewReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostCrewReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewPostCrewNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostCrewBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostCrewUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostCrewInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /crew] PostCrew", response, response.Code())
	}
}

// NewPostCrewNoContent creates a PostCrewNoContent with default headers values
func NewPostCrewNoContent() *PostCrewNoContent {
	return &PostCrewNoContent{}
}

/*
PostCrewNoContent describes a response with status code 204, with default header values.

Success No Content
*/
type PostCrewNoContent struct {
}

// IsSuccess returns true when this post crew no content response has a 2xx status code
func (o *PostCrewNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post crew no content response has a 3xx status code
func (o *PostCrewNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post crew no content response has a 4xx status code
func (o *PostCrewNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this post crew no content response has a 5xx status code
func (o *PostCrewNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this post crew no content response a status code equal to that given
func (o *PostCrewNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the post crew no content response
func (o *PostCrewNoContent) Code() int {
	return 204
}

func (o *PostCrewNoContent) Error() string {
	return fmt.Sprintf("[POST /crew][%d] postCrewNoContent ", 204)
}

func (o *PostCrewNoContent) String() string {
	return fmt.Sprintf("[POST /crew][%d] postCrewNoContent ", 204)
}

func (o *PostCrewNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostCrewBadRequest creates a PostCrewBadRequest with default headers values
func NewPostCrewBadRequest() *PostCrewBadRequest {
	return &PostCrewBadRequest{}
}

/*
PostCrewBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostCrewBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this post crew bad request response has a 2xx status code
func (o *PostCrewBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post crew bad request response has a 3xx status code
func (o *PostCrewBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post crew bad request response has a 4xx status code
func (o *PostCrewBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post crew bad request response has a 5xx status code
func (o *PostCrewBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post crew bad request response a status code equal to that given
func (o *PostCrewBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post crew bad request response
func (o *PostCrewBadRequest) Code() int {
	return 400
}

func (o *PostCrewBadRequest) Error() string {
	return fmt.Sprintf("[POST /crew][%d] postCrewBadRequest  %+v", 400, o.Payload)
}

func (o *PostCrewBadRequest) String() string {
	return fmt.Sprintf("[POST /crew][%d] postCrewBadRequest  %+v", 400, o.Payload)
}

func (o *PostCrewBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostCrewBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostCrewUnauthorized creates a PostCrewUnauthorized with default headers values
func NewPostCrewUnauthorized() *PostCrewUnauthorized {
	return &PostCrewUnauthorized{}
}

/*
PostCrewUnauthorized describes a response with status code 401, with default header values.

Not Authorized
*/
type PostCrewUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this post crew unauthorized response has a 2xx status code
func (o *PostCrewUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post crew unauthorized response has a 3xx status code
func (o *PostCrewUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post crew unauthorized response has a 4xx status code
func (o *PostCrewUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post crew unauthorized response has a 5xx status code
func (o *PostCrewUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post crew unauthorized response a status code equal to that given
func (o *PostCrewUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post crew unauthorized response
func (o *PostCrewUnauthorized) Code() int {
	return 401
}

func (o *PostCrewUnauthorized) Error() string {
	return fmt.Sprintf("[POST /crew][%d] postCrewUnauthorized  %+v", 401, o.Payload)
}

func (o *PostCrewUnauthorized) String() string {
	return fmt.Sprintf("[POST /crew][%d] postCrewUnauthorized  %+v", 401, o.Payload)
}

func (o *PostCrewUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostCrewUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostCrewInternalServerError creates a PostCrewInternalServerError with default headers values
func NewPostCrewInternalServerError() *PostCrewInternalServerError {
	return &PostCrewInternalServerError{}
}

/*
PostCrewInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type PostCrewInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this post crew internal server error response has a 2xx status code
func (o *PostCrewInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post crew internal server error response has a 3xx status code
func (o *PostCrewInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post crew internal server error response has a 4xx status code
func (o *PostCrewInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post crew internal server error response has a 5xx status code
func (o *PostCrewInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post crew internal server error response a status code equal to that given
func (o *PostCrewInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post crew internal server error response
func (o *PostCrewInternalServerError) Code() int {
	return 500
}

func (o *PostCrewInternalServerError) Error() string {
	return fmt.Sprintf("[POST /crew][%d] postCrewInternalServerError  %+v", 500, o.Payload)
}

func (o *PostCrewInternalServerError) String() string {
	return fmt.Sprintf("[POST /crew][%d] postCrewInternalServerError  %+v", 500, o.Payload)
}

func (o *PostCrewInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostCrewInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
