// Code generated by go-swagger; DO NOT EDIT.

package aiapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/Maritime-AI/mai-go-client/models"
)

// NewPostPartnersOrganizationsIDSearchParams creates a new PostPartnersOrganizationsIDSearchParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostPartnersOrganizationsIDSearchParams() *PostPartnersOrganizationsIDSearchParams {
	return &PostPartnersOrganizationsIDSearchParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostPartnersOrganizationsIDSearchParamsWithTimeout creates a new PostPartnersOrganizationsIDSearchParams object
// with the ability to set a timeout on a request.
func NewPostPartnersOrganizationsIDSearchParamsWithTimeout(timeout time.Duration) *PostPartnersOrganizationsIDSearchParams {
	return &PostPartnersOrganizationsIDSearchParams{
		timeout: timeout,
	}
}

// NewPostPartnersOrganizationsIDSearchParamsWithContext creates a new PostPartnersOrganizationsIDSearchParams object
// with the ability to set a context for a request.
func NewPostPartnersOrganizationsIDSearchParamsWithContext(ctx context.Context) *PostPartnersOrganizationsIDSearchParams {
	return &PostPartnersOrganizationsIDSearchParams{
		Context: ctx,
	}
}

// NewPostPartnersOrganizationsIDSearchParamsWithHTTPClient creates a new PostPartnersOrganizationsIDSearchParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostPartnersOrganizationsIDSearchParamsWithHTTPClient(client *http.Client) *PostPartnersOrganizationsIDSearchParams {
	return &PostPartnersOrganizationsIDSearchParams{
		HTTPClient: client,
	}
}

/*
PostPartnersOrganizationsIDSearchParams contains all the parameters to send to the API endpoint

	for the post partners organizations ID search operation.

	Typically these are written to a http.Request.
*/
type PostPartnersOrganizationsIDSearchParams struct {

	// Body.
	Body *models.SearchParams

	/* ID.

	   The unqiue partner organization reference id
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post partners organizations ID search params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostPartnersOrganizationsIDSearchParams) WithDefaults() *PostPartnersOrganizationsIDSearchParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post partners organizations ID search params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostPartnersOrganizationsIDSearchParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post partners organizations ID search params
func (o *PostPartnersOrganizationsIDSearchParams) WithTimeout(timeout time.Duration) *PostPartnersOrganizationsIDSearchParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post partners organizations ID search params
func (o *PostPartnersOrganizationsIDSearchParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post partners organizations ID search params
func (o *PostPartnersOrganizationsIDSearchParams) WithContext(ctx context.Context) *PostPartnersOrganizationsIDSearchParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post partners organizations ID search params
func (o *PostPartnersOrganizationsIDSearchParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post partners organizations ID search params
func (o *PostPartnersOrganizationsIDSearchParams) WithHTTPClient(client *http.Client) *PostPartnersOrganizationsIDSearchParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post partners organizations ID search params
func (o *PostPartnersOrganizationsIDSearchParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post partners organizations ID search params
func (o *PostPartnersOrganizationsIDSearchParams) WithBody(body *models.SearchParams) *PostPartnersOrganizationsIDSearchParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post partners organizations ID search params
func (o *PostPartnersOrganizationsIDSearchParams) SetBody(body *models.SearchParams) {
	o.Body = body
}

// WithID adds the id to the post partners organizations ID search params
func (o *PostPartnersOrganizationsIDSearchParams) WithID(id string) *PostPartnersOrganizationsIDSearchParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the post partners organizations ID search params
func (o *PostPartnersOrganizationsIDSearchParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PostPartnersOrganizationsIDSearchParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
