// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ChatMessage chat message
//
// swagger:model ChatMessage
type ChatMessage struct {

	// created at
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// dynamic response
	DynamicResponse interface{} `json:"dynamic_response,omitempty"`

	// is ai generated
	IsAiGenerated bool `json:"is_ai_generated,omitempty"`

	// message
	Message string `json:"message,omitempty"`

	// ref id
	RefID string `json:"ref_id,omitempty"`

	// references
	References *ChatMessageResponseRefs `json:"references,omitempty"`

	// session id
	SessionID string `json:"session_id,omitempty"`
}

// Validate validates this chat message
func (m *ChatMessage) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateReferences(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ChatMessage) validateCreatedAt(formats strfmt.Registry) error {
	if swag.IsZero(m.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("created_at", "body", "date-time", m.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *ChatMessage) validateReferences(formats strfmt.Registry) error {
	if swag.IsZero(m.References) { // not required
		return nil
	}

	if m.References != nil {
		if err := m.References.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("references")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("references")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this chat message based on the context it is used
func (m *ChatMessage) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateReferences(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ChatMessage) contextValidateReferences(ctx context.Context, formats strfmt.Registry) error {

	if m.References != nil {

		if swag.IsZero(m.References) { // not required
			return nil
		}

		if err := m.References.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("references")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("references")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ChatMessage) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ChatMessage) UnmarshalBinary(b []byte) error {
	var res ChatMessage
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
