// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ChatContext chat context
//
// swagger:model ChatContext
type ChatContext struct {

	// embedding filters
	EmbeddingFilters []*EmbeddingFilter `json:"embedding_filters"`

	// incoming query llm request data
	IncomingQueryLlmRequestData []interface{} `json:"incoming_query_llm_request_data"`

	// merge query llm request data
	MergeQueryLlmRequestData []interface{} `json:"merge_query_llm_request_data"`

	// organization name
	OrganizationName string `json:"organization_name,omitempty"`

	// organization ref id
	OrganizationRefID string `json:"organization_ref_id,omitempty"`

	// parsed incoming query
	ParsedIncomingQuery interface{} `json:"parsed_incoming_query,omitempty"`
}

// Validate validates this chat context
func (m *ChatContext) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEmbeddingFilters(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ChatContext) validateEmbeddingFilters(formats strfmt.Registry) error {
	if swag.IsZero(m.EmbeddingFilters) { // not required
		return nil
	}

	for i := 0; i < len(m.EmbeddingFilters); i++ {
		if swag.IsZero(m.EmbeddingFilters[i]) { // not required
			continue
		}

		if m.EmbeddingFilters[i] != nil {
			if err := m.EmbeddingFilters[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("embedding_filters" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("embedding_filters" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this chat context based on the context it is used
func (m *ChatContext) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateEmbeddingFilters(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ChatContext) contextValidateEmbeddingFilters(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.EmbeddingFilters); i++ {

		if m.EmbeddingFilters[i] != nil {

			if swag.IsZero(m.EmbeddingFilters[i]) { // not required
				return nil
			}

			if err := m.EmbeddingFilters[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("embedding_filters" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("embedding_filters" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ChatContext) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ChatContext) UnmarshalBinary(b []byte) error {
	var res ChatContext
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
