// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ChatListResponse chat list response
//
// swagger:model ChatListResponse
type ChatListResponse struct {

	// header
	Header string `json:"header,omitempty"`

	// texts
	Texts []string `json:"texts"`
}

// Validate validates this chat list response
func (m *ChatListResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this chat list response based on context it is used
func (m *ChatListResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ChatListResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ChatListResponse) UnmarshalBinary(b []byte) error {
	var res ChatListResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
