// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CredentialDetails credential details
//
// swagger:model CredentialDetails
type CredentialDetails struct {

	// The Roman numerals associated with the credential
	RomanNumerals []string `json:"roman_numerals"`

	// The title of the credential
	Title string `json:"title,omitempty"`
}

// Validate validates this credential details
func (m *CredentialDetails) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this credential details based on context it is used
func (m *CredentialDetails) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CredentialDetails) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CredentialDetails) UnmarshalBinary(b []byte) error {
	var res CredentialDetails
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
