// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CrewParams crew params
//
// swagger:model CrewParams
type CrewParams struct {

	// The city of the user
	City *string `json:"city,omitempty"`

	// The unique reference id for the context
	ContextRefID string `json:"context_ref_id,omitempty"`

	// The country of the user
	Country *string `json:"country,omitempty"`

	// The unique external id for the crew
	CrewExternalID string `json:"crew_external_id,omitempty"`

	// The email of the user
	Email *string `json:"email,omitempty"`

	// The first name of the user
	FirstName string `json:"first_name,omitempty"`

	// The job title of the user
	JobTitle *string `json:"job_title,omitempty"`

	// The last name of the user
	LastName string `json:"last_name,omitempty"`

	// The middle name of the user
	MiddleName *string `json:"middle_name,omitempty"`

	// The unique partner organization reference id
	PartnerOrganizationID string `json:"partner_organization_id,omitempty"`

	// The phone of the user
	Phone *string `json:"phone,omitempty"`

	// The state of the user
	State *string `json:"state,omitempty"`
}

// Validate validates this crew params
func (m *CrewParams) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this crew params based on context it is used
func (m *CrewParams) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CrewParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CrewParams) UnmarshalBinary(b []byte) error {
	var res CrewParams
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
