// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CrewRecord crew record
//
// swagger:model CrewRecord
type CrewRecord struct {

	// The city of the user
	City *string `json:"city,omitempty"`

	// The unique reference id for the context
	ContextRefID string `json:"context_ref_id,omitempty"`

	// The country of the user
	Country *string `json:"country,omitempty"`

	// The unique external id for the crew
	CrewExternalID string `json:"crew_external_id,omitempty"`

	// The email of the user
	Email *string `json:"email,omitempty"`

	// The first name of the user
	FirstName string `json:"first_name,omitempty"`

	// The job title of the user
	JobTitle *string `json:"job_title,omitempty"`

	// The last name of the user
	LastName string `json:"last_name,omitempty"`

	// The middle name of the user
	MiddleName *string `json:"middle_name,omitempty"`

	// The phone of the user
	Phone *string `json:"phone,omitempty"`

	// The state of the user
	State *string `json:"state,omitempty"`
}

// Validate validates this crew record
func (m *CrewRecord) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this crew record based on context it is used
func (m *CrewRecord) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CrewRecord) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CrewRecord) UnmarshalBinary(b []byte) error {
	var res CrewRecord
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
