// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Endorsement endorsement
//
// swagger:model Endorsement
type Endorsement struct {

	// capacity
	Capacity string `json:"capacity,omitempty"`

	// limitation
	Limitation string `json:"limitation,omitempty"`

	// regulation
	Regulation string `json:"regulation,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this endorsement
func (m *Endorsement) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this endorsement based on context it is used
func (m *Endorsement) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Endorsement) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Endorsement) UnmarshalBinary(b []byte) error {
	var res Endorsement
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
