// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SearchParams search params
//
// swagger:model SearchParams
type SearchParams struct {

	// crew external ids
	CrewExternalIds []string `json:"crew_external_ids"`

	// limit
	Limit *int64 `json:"limit,omitempty"`

	// offset
	Offset *int64 `json:"offset,omitempty"`

	// query
	Query string `json:"query,omitempty"`
}

// Validate validates this search params
func (m *SearchParams) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this search params based on context it is used
func (m *SearchParams) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SearchParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SearchParams) UnmarshalBinary(b []byte) error {
	var res SearchParams
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
