// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SearchHitInfo search hit info
//
// swagger:model SearchHitInfo
type SearchHitInfo struct {

	// hit type
	HitType string `json:"hit_type,omitempty"`

	// reference external id
	ReferenceExternalID string `json:"reference_external_id,omitempty"`

	// text
	Text string `json:"text,omitempty"`
}

// Validate validates this search hit info
func (m *SearchHitInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this search hit info based on context it is used
func (m *SearchHitInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SearchHitInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SearchHitInfo) UnmarshalBinary(b []byte) error {
	var res SearchHitInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
